version: 2.1

jobs:
  quality:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: "Check code quality"
          command: |
            pip install flake8
            flake8
  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: "Run pytest"
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
            export PATH="/root/.local/bin:$PATH"
            poetry install
            poetry run pytest tests/

workflows:
  check-code:
    jobs:
      - quality
      - test
